"""change_user_table

Revision ID: 9ba5412dd561
Revises: dcc9e7419048
Create Date: 2025-09-19 19:50:44.451561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba5412dd561'
down_revision: Union[str, Sequence[str], None] = 'dcc9e7419048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Addresses', 'street',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Addresses', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Addresses', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('Users', sa.Column('firstname', sa.String(length=200), nullable=False))
    op.add_column('Users', sa.Column('lastname', sa.String(length=200), nullable=False))
    op.drop_column('Users', 'fullname')
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'lastname')
    op.drop_column('Users', 'firstname')
    op.alter_column('Addresses', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Addresses', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Addresses', 'street',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
