"""init

Revision ID: dcc9e7419048
Revises: 
Create Date: 2025-09-19 15:00:27.349604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc9e7419048'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Addresses', sa.Column('userid', sa.Integer(), nullable=True))
    op.alter_column('Addresses', 'street',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('Addresses', 'city',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('Addresses_user_id_fkey'), 'Addresses', type_='foreignkey')
    op.create_foreign_key(None, 'Addresses', 'Users', ['userid'], ['id'])
    op.drop_column('Addresses', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Addresses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Addresses', type_='foreignkey')
    op.create_foreign_key(op.f('Addresses_user_id_fkey'), 'Addresses', 'Users', ['user_id'], ['id'])
    op.alter_column('Addresses', 'city',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Addresses', 'street',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('Addresses', 'userid')
    # ### end Alembic commands ###
